openapi: 3.0.0
info:
  version: 1.0.0
  title: Stellarium
servers:
  - url: 'localhost/api'
paths:
    /login:
        post:
            description: Authenticate the user and returns the session cookie
            security: []
            responses:
                '200':
                    description: >
                        Successfully authenticated.
                        The session ID is returned in a cookie named `adonis-session`. You need to include this cookie in subsequent requests.
                        If the remeber me token is required it will be returned along the session cookie.
                    headers:
                        Set-Cookie:
                            schema:
                                type: string
                                example: adonis-session=abcde1234; Path=/; HttpOnly
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: Connected
    /logout:
        get:
            description: Logs out the user
            responses:
                '200': 
                    description: Successfully logged out the user
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: Disconnected
components:
  securitySchemes:
    cookieAuth:
        type: apiKey
        in: cookie
        name: adonis-session
security:
  - cookieAuth: []